package aprofplot.gui;

import java.awt.BorderLayout;
import java.awt.event.*;
import javax.swing.*;
import aprofplot.*;
import javax.swing.event.*;

public class SettingsDialog extends javax.swing.JDialog {

	/** Creates new form SettingsDialog */
	public SettingsDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		setSize(450, 350);
		setLocationRelativeTo(parent);
		boolean blacklist_enabled = Main.getBlackListEnabled();
		jCheckBox1.setSelected(blacklist_enabled);
		jTextArea1.setEnabled(blacklist_enabled);
		java.util.ArrayList<String> blacklist = Main.getBlackList();
		for (int i = 0; i < blacklist.size(); i++) jTextArea1.append(blacklist.get(i) + ", ");
		if (Main.getRtnDisplayMode() == Main.DEMANGLED) jRadioButton1.setSelected(true);
		else jRadioButton2.setSelected(true);
		jButton2.setEnabled(false);
		this.setResizable(false);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new ButtonGroup();
        jTabbedPane1 = new JTabbedPane();
        jPanel4 = new JPanel();
        jRadioButton1 = new JRadioButton();
        jRadioButton2 = new JRadioButton();
        jPanel1 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jTextArea1 = new JTextArea();
        jPanel3 = new JPanel();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jCheckBox1 = new JCheckBox();
        jPanel2 = new JPanel();
        jButton1 = new JButton();
        jButton2 = new JButton();
        jButton3 = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");

        jTabbedPane1.setBorder(BorderFactory.createEmptyBorder(2, 2, 2, 2));

        jPanel4.setBorder(BorderFactory.createTitledBorder("Routine naming policy"));
        jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Show demangled names ");
        jRadioButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Show demangled names with full signature ");
        jRadioButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jRadioButton2);

        jTabbedPane1.addTab("Display", jPanel4);

        jPanel1.setLayout(new BorderLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                // text was changed
                jButton2.setEnabled(true);
            }
            public void removeUpdate(DocumentEvent e) {
                // text was deleted
                jButton2.setEnabled(true);
            }
            public void insertUpdate(DocumentEvent e) {
                // text was inserted
                jButton2.setEnabled(true);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, BorderLayout.CENTER);

        jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.Y_AXIS));

        jLabel1.setText("Routines whose name is blacklisted won't be displayed.");
        jPanel3.add(jLabel1);

        jLabel2.setText("Entries must be comma-separated.");
        jPanel3.add(jLabel2);

        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Enable routine blacklist");
        jCheckBox1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1);

        jPanel1.add(jPanel3, BorderLayout.PAGE_START);

        jTabbedPane1.addTab("Routine blacklist", jPanel1);

        getContentPane().add(jTabbedPane1, BorderLayout.CENTER);

        jPanel2.setBorder(BorderFactory.createEmptyBorder(2, 2, 4, 4));
        jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.LINE_AXIS));

        jButton1.setText("   Ok   ");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(Box.createHorizontalGlue());
        jPanel2.add(jButton1);

        jButton2.setText(" Apply ");
        jButton2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton3.setText("Cancel");
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);

        getContentPane().add(jPanel2, BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void save() {
		java.util.ArrayList<String> blacklist = new java.util.ArrayList<String>();
		String list = jTextArea1.getText().trim();
		if (!list.equals("")) {
			java.util.StringTokenizer tokenizer = new java.util.StringTokenizer(list, ",");
			while (tokenizer.hasMoreTokens()) {
				blacklist.add(tokenizer.nextToken().trim());
			}
		}
		if (jRadioButton1.isSelected()) Main.storeRtnDisplayMode(Main.DEMANGLED);
		else Main.storeRtnDisplayMode(Main.DEMANGLED_FULL);
		Main.storeBlacklist(blacklist, jCheckBox1.isSelected());
		((MainWindow)getParent()).refreshRoutinesTableFilter();
	}
	
	private void jCheckBox1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
		// Enable/disable blacklist checkbox
		jTextArea1.setEnabled(jCheckBox1.isSelected());
		jButton2.setEnabled(true);
	}//GEN-LAST:event_jCheckBox1ActionPerformed

	private void jButton3ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
		// Cancel button
		this.dispose();
	}//GEN-LAST:event_jButton3ActionPerformed

	private void jButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
		// Apply button
		save();
		jButton2.setEnabled(false);
	}//GEN-LAST:event_jButton2ActionPerformed

	private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		// Ok button
		if (jButton2.isEnabled()) save();
		this.dispose();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jRadioButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
		// demangled names
		jButton2.setEnabled(true);
	}//GEN-LAST:event_jRadioButton1ActionPerformed

	private void jRadioButton2ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
		// Full demangled names
		jButton2.setEnabled(true);
	}//GEN-LAST:event_jRadioButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup buttonGroup1;
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JCheckBox jCheckBox1;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    private JPanel jPanel4;
    private JRadioButton jRadioButton1;
    private JRadioButton jRadioButton2;
    private JScrollPane jScrollPane1;
    private JTabbedPane jTabbedPane1;
    private JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
